# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
joint21_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint21
  pid: {p: 10.0, i: 1.0, d: 0.005}
joint32_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint32
  pid: {p: 10.0, i: 1.0, d: 0.005}
joint43_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint43
  pid: {p: 10.0, i: 1.0, d: 0.005}
joint54_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint54
  pid: {p: 10.0, i: 1.0, d: 0.005}
joint65_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint65
  pid: {p: 10.0, i: 1.0, d: 0.005}
wrist_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_joint
  pid: {p: 10.0, i: 1.0, d: 0.005}
hand_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_finger_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
