controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint21
      - joint32
      - joint43
      - joint54
      - joint65
      - wrist_joint
  - name: gripper_group_controller
    action_ns: gripper_action
    default: True
    type: GripperCommand
    joints:
      right_finger_joint
