# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint21:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  joint32:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0
  joint43:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0
  joint54:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0
  joint65:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0