# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: mycobot_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - joint21
    - joint32
    - joint43
    - joint54
    - joint65
    - wrist_joint
    - right_finger_joint
    - left_track_motor
    - right_track_motor
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

mycobot_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint21
    - joint32
    - joint43
    - joint54
    - joint65
    - wrist_joint
  gains:
    joint21: { p: 10.0, d: 0.0, i: 0.0 }
    joint32: { p: 10.0, d: 0.0, i: 0.0 }
    joint43: { p: 10.0, d: 0.0, i: 0.0 }
    joint54: { p: 10.0, d: 0.0, i: 0.0 }
    joint65: { p: 10.0, d:  0.0, i: 0.0 }
    wrist_joint: { p: 10.0, d: 0.0, i: 0.0 }

  state_publish_rate: 50
  constraints:
    goal_time: 2.0

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_finger_joint
  gains:
    right_finger_joint: { p: 1.0, i: 0.0, d: 0.0 }

  state_publish_rate: 50
  constraints:
    goal_time: 2.0
        
controller_list:
  - name: mycobot_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint21
      - joint32
      - joint43
      - joint54
      - joint65
      - wrist_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_finger_joint
